-- Content protection security event types (audit / deterrence)

ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'RIGHT_CLICK_BLOCKED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'COPY_BLOCKED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'PRINT_BLOCKED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'SELECT_ALL_BLOCKED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'SCREENSHOT_ATTEMPT';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'DEVTOOLS_OPENED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'DEVTOOLS_CLOSED';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'FULLSCREEN_EXIT';
ALTER TYPE "LearningEventType" ADD VALUE IF NOT EXISTS 'SAVE_BLOCKED';
